# Generated by Django 5.2.5 on 2025-08-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('bmi', models.FloatField()),
                ('children', models.FloatField()),
                ('sex_male', models.IntegerField()),
                ('smoker_yes', models.FloatField()),
                ('region_southeast', models.FloatField()),
            ],
        ),
    ]
